# Generated by Django 3.0.7 on 2020-06-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predresults',
            name='classification',
        ),
    ]
